spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.postgresql.Driver
    #password: example
    #username: root
    url: jdbc:derby:derby/example;create=true
    #url: jdbc:mysql://localhost:3306/example
    #url: jdbc:postgresql://localhost:5432/example
#    hikari:
#      data-source-class-name: org.apache.derby.jdbc.ClientDataSource

app:
  users:
    - name: admin
      password: "{noop}admin"
      roles:
        - ADMIN
    - name: user
      password: "{noop}partner"
      roles:
        - ADMIN
        - USER
    - name: jose
      #password: myPassword
      password: "{bcrypt}$2a$16$el8CA9O1lm55Xh8Bmm8ZjOJSO2ygd8eQEkY7dvk6OQ5m.LVoy/jTi"
      roles:
        - ADMIN
        - USER